"""Corrigindo colunas

Revision ID: be919fbe7357
Revises: bf7ae5feca39
Create Date: 2025-11-26 19:26:13.966118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be919fbe7357'
down_revision: Union[str, Sequence[str], None] = 'bf7ae5feca39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('self', sa.String(), nullable=True))
    op.add_column('usuario', sa.Column('ativo', sa.Boolean(), nullable=True))
    op.add_column('usuario', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'admin')
    op.drop_column('usuario', 'ativo')
    op.drop_column('usuario', 'self')
    # ### end Alembic commands ###
